### ISSUE TITLE
Missing rosbag file

### ISSUE THREAD

**Issue by enrparsan** [samialperen/oko_slam#2]
The third tutorial of  doc/gmapping_tutorial.md it's said that there is a rosbag file but the link is broken, I guess the actual rosbag file was in oko_slam/ros_ws/bagfiles/real_data but there isn't any real_data subdirectory.

**Comment by ozzdemir** [comment]
Those bag files were not committed to the repo for storage issues, for that tutorial, that specific bag is not required but any bag with scan topic is possible as stated in the tutorial. If you don't have one at hand, you can use the added [simulation recordings](https://github.com/samialperen/oko_slam/tree/master/ros_ws/bagfiles/simulation_data). But if you specifically interested in the hardware recordings from the custom scanner we built, it is another issue and please feel free to re-open the issue.

> Run the bagfile you record. You might record this bagfile during either in simulation or real world. For example, we recorded [a bag file](https://github.com/samialperen/oko_slam/blob/master/ros_ws/bagfiles/real_data/realmap3objects-linearvel30-lidar-4hz2.bag) which contains only laser scan data in /scan topic. We used Turtlebot3 in Gazebo to record this bag file. However, you can use **any bagfile you want**.
